### ISSUE TITLE
Landing page renders incorrectly when viewed on mobile

### ISSUE THREAD

**Issue by forstmeier** [forstmeier/quehook#6]
#### Description (1-2 sentences)
As far as I can tell, the [landing page](https://forstmeier.github.io/comana/) is continuing to display incorrectly when viewed on a phone. This isn't a huge deal, since this application can only really be used while on a laptop/desktop, but I'd like to correct it anyway.

#### Specifics (bullet points)
- [ ] site should not "scruntch" when viewed on mobile
- [ ] "body" section should fit closer to the device edges (see below)
<img width="566" alt="Screen Shot 2019-09-02 at 10 50 16 AM" src="https://user-images.githubusercontent.com/13358530/64122387-7d5fb900-cd6f-11e9-9b7d-5cd4fef175e2.png">

**Comment by juanfrank7** [comment]
Hey! Since the front-end is my thing, I can take a look at it and give it a shot. 
I could be doing it after work, give me a day or two and I'll let you know.

**Comment by forstmeier** [comment]
@juanfrank7 Awesome! I'm looking for ways to just generally clean up the frontend static landing page so I'm also open to additional suggestions for improvements.

**Comment by juanfrank7** [comment]
Alright mate, I'll look into it and see what else can be improved. Visually or code wise.
